// Helper functions for working with Lucide icons
import * as lucideIcons from 'lucide';

export interface LucideIconData {
  name: string;
  svg: string;
  keywords: string[];
  categories: string[];
}

export async function getAllLucideIcons(): Promise<Record<string, LucideIconData>> {
  const icons: Record<string, LucideIconData> = {};
  
  // Get all icon names from lucide package
  const iconNames = Object.keys(lucideIcons).filter(name => 
    name !== 'createLucideIcon' && 
    name !== 'Icon' &&
    typeof (lucideIcons as any)[name] === 'object'
  );
  
  for (const iconName of iconNames) {
    try {
      const icon = (lucideIcons as any)[iconName];
      if (icon && typeof icon === 'object') {
        // Convert camelCase to kebab-case for icon name
        const kebabName = iconName.replace(/([A-Z])/g, '-$1').toLowerCase();
        
        icons[kebabName] = {
          name: kebabName,
          svg: generateSvgString(icon, kebabName),
          keywords: getIconKeywords(kebabName),
          categories: getIconCategories(kebabName)
        };
      }
    } catch (error) {
      console.warn(`Could not process icon ${iconName}:`, error);
    }
  }
  
  return icons;
}

function generateSvgString(iconData: any, iconName: string): string {
  // This is a simplified SVG generation
  // In practice, you'd want to use the actual Lucide icon data
  return `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-${iconName}">
    <!-- Icon paths would be here -->
  </svg>`;
}

function getIconKeywords(iconName: string): string[] {
  // This would ideally come from Lucide's metadata
  const keywordMap: Record<string, string[]> = {
    'home': ['house', 'building', 'residence', 'homepage', 'main'],
    'user': ['person', 'profile', 'account', 'avatar', 'individual'],
    'search': ['find', 'look', 'magnifying glass', 'query', 'explore'],
    'heart': ['love', 'like', 'favorite', 'romance', 'health'],
    'star': ['rating', 'bookmark', 'favorite', 'quality', 'award'],
    'settings': ['config', 'preferences', 'gear', 'options', 'configure'],
    'menu': ['hamburger', 'navigation', 'list', 'options', 'drawer'],
    'plus': ['add', 'create', 'new', 'positive', 'increase'],
    'minus': ['subtract', 'remove', 'negative', 'less', 'decrease'],
    'x': ['close', 'cancel', 'delete', 'cross', 'exit'],
    'check': ['confirm', 'approve', 'done', 'success', 'complete'],
    'arrow-right': ['next', 'forward', 'continue', 'proceed', 'east'],
    'arrow-left': ['back', 'previous', 'return', 'west', 'retreat'],
    'arrow-up': ['north', 'increase', 'rise', 'top', 'ascend'],
    'arrow-down': ['south', 'decrease', 'fall', 'bottom', 'descend'],
    'download': ['save', 'export', 'get', 'receive', 'pull'],
    'upload': ['send', 'import', 'put', 'transmit', 'push'],
    'edit': ['modify', 'change', 'update', 'pencil', 'write'],
    'delete': ['remove', 'trash', 'erase', 'destroy', 'eliminate'],
    'copy': ['duplicate', 'clone', 'replicate', 'reproduce', 'mirror'],
    'share': ['distribute', 'send', 'spread', 'broadcast', 'network'],
    'lock': ['secure', 'protect', 'encrypt', 'private', 'closed'],
    'unlock': ['open', 'access', 'decrypt', 'public', 'available'],
    'eye': ['view', 'see', 'visible', 'watch', 'observe'],
    'eye-off': ['hide', 'invisible', 'private', 'conceal', 'blind'],
    'mail': ['email', 'message', 'letter', 'envelope', 'communication'],
    'phone': ['call', 'telephone', 'contact', 'mobile', 'communication'],
    'calendar': ['date', 'schedule', 'time', 'event', 'appointment'],
    'clock': ['time', 'hour', 'minute', 'schedule', 'timer'],
    'camera': ['photo', 'picture', 'image', 'capture', 'snapshot'],
    'image': ['picture', 'photo', 'graphic', 'visual', 'media'],
    'video': ['movie', 'film', 'clip', 'recording', 'media'],
    'music': ['audio', 'sound', 'song', 'melody', 'entertainment'],
    'volume': ['sound', 'audio', 'speaker', 'noise', 'level'],
    'wifi': ['internet', 'connection', 'network', 'wireless', 'signal'],
    'bluetooth': ['wireless', 'connection', 'pairing', 'device', 'sync'],
    'battery': ['power', 'charge', 'energy', 'electricity', 'life'],
    'sun': ['light', 'bright', 'day', 'weather', 'solar'],
    'moon': ['night', 'dark', 'sleep', 'lunar', 'evening'],
    'cloud': ['weather', 'sky', 'storage', 'online', 'backup'],
    'umbrella': ['rain', 'weather', 'protection', 'shield', 'cover'],
    'car': ['vehicle', 'automobile', 'transport', 'drive', 'travel'],
    'plane': ['aircraft', 'flight', 'travel', 'aviation', 'transport'],
    'train': ['railway', 'transport', 'travel', 'locomotive', 'commute'],
    'bike': ['bicycle', 'transport', 'exercise', 'cycling', 'eco'],
    'shopping-cart': ['purchase', 'buy', 'store', 'ecommerce', 'basket'],
    'credit-card': ['payment', 'money', 'finance', 'purchase', 'banking'],
    'dollar-sign': ['money', 'currency', 'price', 'cost', 'finance'],
    'gift': ['present', 'surprise', 'celebration', 'reward', 'bonus'],
    'trophy': ['award', 'prize', 'achievement', 'victory', 'success'],
    'flag': ['banner', 'country', 'signal', 'marker', 'alert'],
    'map': ['location', 'geography', 'navigation', 'directions', 'area'],
    'map-pin': ['location', 'marker', 'address', 'place', 'coordinates'],
    'compass': ['direction', 'navigation', 'orientation', 'guide', 'path'],
    'globe': ['world', 'earth', 'international', 'global', 'planet'],
    'building': ['office', 'structure', 'architecture', 'company', 'tower'],
    'school': ['education', 'learning', 'university', 'college', 'academic'],
    'hospital': ['medical', 'health', 'care', 'doctor', 'emergency'],
    'store': ['shop', 'retail', 'market', 'business', 'commerce'],
    'book': ['read', 'literature', 'education', 'knowledge', 'library'],
    'bookmark': ['save', 'favorite', 'mark', 'remember', 'reference'],
    'file': ['document', 'paper', 'record', 'data', 'storage'],
    'folder': ['directory', 'organize', 'container', 'group', 'category'],
    'paperclip': ['attach', 'link', 'connect', 'join', 'fasten'],
    'scissors': ['cut', 'trim', 'clip', 'divide', 'separate'],
    'printer': ['print', 'output', 'paper', 'document', 'hard-copy'],
    'scanner': ['scan', 'input', 'digitize', 'copy', 'capture'],
    'monitor': ['screen', 'display', 'computer', 'desktop', 'view'],
    'smartphone': ['mobile', 'phone', 'device', 'cellular', 'portable'],
    'tablet': ['device', 'mobile', 'touch', 'portable', 'screen'],
    'laptop': ['computer', 'portable', 'notebook', 'mobile', 'device'],
    'keyboard': ['input', 'type', 'computer', 'keys', 'interface'],
    'mouse': ['pointer', 'click', 'computer', 'cursor', 'interface'],
    'headphones': ['audio', 'listen', 'music', 'sound', 'private'],
    'microphone': ['audio', 'record', 'voice', 'input', 'sound'],
    'speaker': ['audio', 'sound', 'output', 'volume', 'play'],
    'game-controller': ['gaming', 'play', 'controller', 'entertainment', 'joystick'],
    'tv': ['television', 'screen', 'entertainment', 'media', 'broadcast'],
    'radio': ['audio', 'broadcast', 'music', 'news', 'wireless'],
    'router': ['network', 'internet', 'wifi', 'connection', 'modem'],
    'server': ['computer', 'network', 'database', 'hosting', 'cloud'],
    'database': ['data', 'storage', 'information', 'server', 'records'],
    'code': ['programming', 'development', 'script', 'software', 'syntax'],
    'terminal': ['command', 'console', 'shell', 'cli', 'interface'],
    'git-branch': ['version', 'control', 'development', 'merge', 'code'],
    'github': ['repository', 'code', 'development', 'version', 'open-source'],
    'package': ['box', 'delivery', 'shipping', 'container', 'bundle'],
    'truck': ['delivery', 'transport', 'shipping', 'cargo', 'logistics'],
    'rocket': ['launch', 'fast', 'startup', 'space', 'speed'],
    'target': ['goal', 'aim', 'focus', 'objective', 'bullseye'],
    'trend-up': ['growth', 'increase', 'success', 'profit', 'improvement'],
    'trend-down': ['decline', 'decrease', 'loss', 'reduction', 'fall'],
    'bar-chart': ['data', 'statistics', 'analytics', 'graph', 'metrics'],
    'pie-chart': ['data', 'statistics', 'analytics', 'percentage', 'distribution'],
    'activity': ['pulse', 'health', 'monitor', 'vital', 'heartbeat'],
    'thermometer': ['temperature', 'heat', 'cold', 'weather', 'fever'],
    'droplet': ['water', 'liquid', 'rain', 'humidity', 'fluid'],
    'flame': ['fire', 'hot', 'burn', 'heat', 'energy'],
    'zap': ['lightning', 'electric', 'power', 'energy', 'bolt'],
    'leaf': ['nature', 'plant', 'eco', 'green', 'environment'],
    'tree': ['nature', 'plant', 'forest', 'environment', 'growth'],
    'flower': ['nature', 'plant', 'beauty', 'bloom', 'garden'],
    'snowflake': ['winter', 'cold', 'snow', 'ice', 'unique'],
    'coffee': ['drink', 'caffeine', 'morning', 'energy', 'beverage'],
    'pizza': ['food', 'meal', 'italian', 'slice', 'dinner'],
    'ice-cream': ['dessert', 'sweet', 'cold', 'treat', 'summer'],
    'birthday-cake': ['celebration', 'party', 'birthday', 'sweet', 'dessert'],
    'wine': ['drink', 'alcohol', 'celebration', 'grape', 'beverage'],
    'beer': ['drink', 'alcohol', 'pub', 'beverage', 'social'],
    'utensils': ['eating', 'food', 'cutlery', 'dining', 'meal'],
    'chef-hat': ['cooking', 'chef', 'kitchen', 'food', 'culinary'],
    'apple': ['fruit', 'healthy', 'food', 'nutrition', 'fresh'],
    'carrot': ['vegetable', 'healthy', 'food', 'nutrition', 'orange'],
    'shirt': ['clothing', 'wear', 'fashion', 'dress', 'apparel'],
    'crown': ['royalty', 'king', 'queen', 'luxury', 'authority'],
    'glasses': ['eyewear', 'vision', 'reading', 'smart', 'intellectual'],
    'watch': ['time', 'clock', 'wrist', 'schedule', 'punctual'],
    'ring': ['jewelry', 'marriage', 'circular', 'precious', 'engagement'],
    'gem': ['diamond', 'precious', 'valuable', 'jewelry', 'crystal'],
    'hammer': ['tool', 'build', 'construction', 'repair', 'work'],
    'wrench': ['tool', 'repair', 'fix', 'maintenance', 'mechanic'],
    'screwdriver': ['tool', 'repair', 'fix', 'build', 'maintenance'],
    'paintbrush': ['art', 'creative', 'paint', 'design', 'artistic'],
    'palette': ['art', 'color', 'creative', 'design', 'painting'],
    'music-note': ['melody', 'song', 'tune', 'musical', 'sound'],
    'guitar': ['music', 'instrument', 'string', 'acoustic', 'rock'],
    'piano': ['music', 'instrument', 'keys', 'classical', 'melody'],
    'drum': ['music', 'instrument', 'beat', 'rhythm', 'percussion'],
    'soccer-ball': ['football', 'sport', 'game', 'ball', 'team'],
    'basketball': ['sport', 'game', 'ball', 'team', 'court'],
    'tennis-ball': ['sport', 'game', 'racket', 'court', 'yellow'],
    'bowling-ball': ['sport', 'game', 'alley', 'pins', 'strike'],
    'dumbbell': ['fitness', 'exercise', 'weight', 'strength', 'gym'],
    'bicycle': ['bike', 'transport', 'exercise', 'eco', 'pedal'],
    'running': ['exercise', 'fitness', 'sport', 'jog', 'marathon'],
    'swimming': ['sport', 'water', 'pool', 'exercise', 'stroke'],
    'mountain': ['nature', 'landscape', 'peak', 'hiking', 'adventure'],
    'tent': ['camping', 'outdoor', 'shelter', 'adventure', 'nature'],
    'campfire': ['outdoor', 'camping', 'warmth', 'cooking', 'gathering'],
    'fish': ['ocean', 'sea', 'aquatic', 'swimming', 'seafood'],
    'anchor': ['ship', 'boat', 'sea', 'stability', 'naval'],
    'sailboat': ['boat', 'sailing', 'ocean', 'wind', 'recreation'],
    'lighthouse': ['navigation', 'safety', 'beacon', 'coast', 'guidance'],
    'bridge': ['connection', 'crossing', 'architecture', 'transport', 'link'],
    'castle': ['fortress', 'medieval', 'palace', 'royal', 'historic'],
    'church': ['religious', 'worship', 'building', 'spiritual', 'community'],
    'graduation-cap': ['education', 'degree', 'achievement', 'learning', 'academic'],
    'medal': ['award', 'achievement', 'honor', 'recognition', 'prize'],
    'ribbon': ['award', 'decoration', 'celebration', 'honor', 'achievement'],
    'balloon': ['party', 'celebration', 'fun', 'festive', 'air'],
    'confetti': ['celebration', 'party', 'joy', 'festive', 'colorful'],
    'fireworks': ['celebration', 'explosion', 'party', 'festival', 'display'],
    'party-popper': ['celebration', 'party', 'confetti', 'fun', 'festive'],
    'mask': ['disguise', 'theater', 'costume', 'protection', 'anonymous'],
    'ghost': ['spirit', 'halloween', 'spooky', 'supernatural', 'phantom'],
    'skull': ['death', 'danger', 'warning', 'pirate', 'skeleton'],
    'robot': ['artificial', 'intelligence', 'automation', 'technology', 'android'],
    'alien': ['extraterrestrial', 'space', 'ufo', 'foreign', 'unknown'],
    'rocket-ship': ['space', 'launch', 'exploration', 'travel', 'blast-off'],
    'satellite': ['space', 'communication', 'orbit', 'technology', 'signal'],
    'telescope': ['astronomy', 'space', 'observation', 'stars', 'discovery'],
    'microscope': ['science', 'research', 'laboratory', 'study', 'analysis'],
    'test-tube': ['science', 'chemistry', 'experiment', 'laboratory', 'research'],
    'dna': ['genetics', 'biology', 'science', 'heredity', 'molecular'],
    'atom': ['science', 'physics', 'nuclear', 'particle', 'chemistry'],
    'magnet': ['attraction', 'force', 'physics', 'pull', 'magnetic'],
    'balance': ['scale', 'justice', 'equality', 'weight', 'fairness'],
    'gavel': ['justice', 'law', 'court', 'judge', 'legal'],
    'briefcase': ['business', 'work', 'professional', 'office', 'career'],
    'handshake': ['agreement', 'partnership', 'deal', 'cooperation', 'greeting'],
    'thumbs-up': ['approval', 'like', 'good', 'positive', 'agreement'],
    'thumbs-down': ['disapproval', 'dislike', 'bad', 'negative', 'rejection'],
    'clap': ['applause', 'appreciation', 'celebration', 'approval', 'praise'],
    'wave': ['greeting', 'hello', 'goodbye', 'gesture', 'friendly'],
    'peace': ['harmony', 'calm', 'tranquil', 'non-violence', 'serenity'],
    'victory': ['win', 'success', 'triumph', 'achievement', 'celebration'],
    'punch': ['fight', 'force', 'strength', 'combat', 'power'],
    'muscle': ['strength', 'power', 'fitness', 'strong', 'flex']
  };
  
  return keywordMap[iconName] || [];
}

function getIconCategories(iconName: string): string[] {
  // This would ideally come from Lucide's metadata
  const categoryMap: Record<string, string[]> = {
    'home': ['navigation', 'buildings'],
    'user': ['users', 'profiles'],
    'search': ['interface', 'tools'],
    'heart': ['health', 'emotions'],
    'star': ['interface', 'ratings'],
    'settings': ['interface', 'tools'],
    'menu': ['interface', 'navigation'],
    'plus': ['interface', 'math'],
    'minus': ['interface', 'math'],
    'x': ['interface'],
    'check': ['interface'],
    'arrow-right': ['arrows', 'navigation'],
    'arrow-left': ['arrows', 'navigation'],
    'arrow-up': ['arrows', 'navigation'],
    'arrow-down': ['arrows', 'navigation'],
    'download': ['interface', 'files'],
    'upload': ['interface', 'files'],
    'edit': ['interface', 'tools'],
    'delete': ['interface'],
    'copy': ['interface'],
    'share': ['interface', 'social'],
    'lock': ['security'],
    'unlock': ['security'],
    'eye': ['interface'],
    'eye-off': ['interface'],
    'mail': ['communication'],
    'phone': ['communication', 'devices'],
    'calendar': ['time', 'organization'],
    'clock': ['time'],
    'camera': ['devices', 'media'],
    'image': ['media'],
    'video': ['media'],
    'music': ['media', 'entertainment'],
    'volume': ['media', 'interface'],
    'wifi': ['connectivity'],
    'bluetooth': ['connectivity'],
    'battery': ['devices'],
    'sun': ['weather', 'nature'],
    'moon': ['weather', 'nature'],
    'cloud': ['weather', 'nature'],
    'umbrella': ['weather'],
    'car': ['transportation'],
    'plane': ['transportation'],
    'train': ['transportation'],
    'bike': ['transportation', 'sports'],
    'shopping-cart': ['commerce'],
    'credit-card': ['finance', 'commerce'],
    'dollar-sign': ['finance'],
    'gift': ['celebration'],
    'trophy': ['awards', 'sports'],
    'flag': ['symbols'],
    'map': ['navigation', 'location'],
    'map-pin': ['navigation', 'location'],
    'compass': ['navigation'],
    'globe': ['location', 'global'],
    'building': ['buildings'],
    'school': ['buildings', 'education'],
    'hospital': ['buildings', 'health'],
    'store': ['buildings', 'commerce'],
    'book': ['education', 'media'],
    'bookmark': ['interface'],
    'file': ['files'],
    'folder': ['files'],
    'paperclip': ['interface'],
    'scissors': ['tools'],
    'printer': ['devices'],
    'scanner': ['devices'],
    'monitor': ['devices'],
    'smartphone': ['devices'],
    'tablet': ['devices'],
    'laptop': ['devices'],
    'keyboard': ['devices'],
    'mouse': ['devices'],
    'headphones': ['devices', 'media'],
    'microphone': ['devices', 'media'],
    'speaker': ['devices', 'media'],
    'game-controller': ['devices', 'entertainment'],
    'tv': ['devices', 'media'],
    'radio': ['devices', 'media'],
    'router': ['devices', 'connectivity'],
    'server': ['devices', 'technology'],
    'database': ['technology'],
    'code': ['development'],
    'terminal': ['development'],
    'git-branch': ['development'],
    'github': ['development', 'brands'],
    'package': ['shipping'],
    'truck': ['transportation', 'shipping'],
    'rocket': ['transportation', 'space'],
    'target': ['interface'],
    'trend-up': ['charts'],
    'trend-down': ['charts'],
    'bar-chart': ['charts'],
    'pie-chart': ['charts'],
    'activity': ['health', 'charts'],
    'thermometer': ['weather', 'health'],
    'droplet': ['nature', 'weather'],
    'flame': ['nature'],
    'zap': ['weather', 'energy'],
    'leaf': ['nature'],
    'tree': ['nature'],
    'flower': ['nature'],
    'snowflake': ['weather', 'nature'],
    'coffee': ['food'],
    'pizza': ['food'],
    'ice-cream': ['food'],
    'birthday-cake': ['food', 'celebration'],
    'wine': ['food'],
    'beer': ['food'],
    'utensils': ['food'],
    'chef-hat': ['food'],
    'apple': ['food'],
    'carrot': ['food'],
    'shirt': ['clothing'],
    'crown': ['clothing', 'symbols'],
    'glasses': ['clothing'],
    'watch': ['clothing', 'time'],
    'ring': ['clothing'],
    'gem': ['symbols'],
    'hammer': ['tools'],
    'wrench': ['tools'],
    'screwdriver': ['tools'],
    'paintbrush': ['art', 'tools'],
    'palette': ['art'],
    'music-note': ['music'],
    'guitar': ['music'],
    'piano': ['music'],
    'drum': ['music'],
    'soccer-ball': ['sports'],
    'basketball': ['sports'],
    'tennis-ball': ['sports'],
    'bowling-ball': ['sports'],
    'dumbbell': ['sports', 'fitness'],
    'bicycle': ['sports', 'transportation'],
    'running': ['sports', 'fitness'],
    'swimming': ['sports'],
    'mountain': ['nature', 'travel'],
    'tent': ['travel', 'camping'],
    'campfire': ['travel', 'camping'],
    'fish': ['animals', 'nature'],
    'anchor': ['nautical'],
    'sailboat': ['nautical', 'transportation'],
    'lighthouse': ['nautical', 'buildings'],
    'bridge': ['buildings', 'transportation'],
    'castle': ['buildings'],
    'church': ['buildings'],
    'graduation-cap': ['education'],
    'medal': ['awards'],
    'ribbon': ['awards'],
    'balloon': ['celebration'],
    'confetti': ['celebration'],
    'fireworks': ['celebration'],
    'party-popper': ['celebration'],
    'mask': ['entertainment'],
    'ghost': ['halloween'],
    'skull': ['halloween', 'symbols'],
    'robot': ['technology'],
    'alien': ['space'],
    'rocket-ship': ['space', 'transportation'],
    'satellite': ['space', 'technology'],
    'telescope': ['science', 'space'],
    'microscope': ['science'],
    'test-tube': ['science'],
    'dna': ['science'],
    'atom': ['science'],
    'magnet': ['science'],
    'balance': ['justice', 'tools'],
    'gavel': ['justice'],
    'briefcase': ['business'],
    'handshake': ['business', 'gestures'],
    'thumbs-up': ['gestures'],
    'thumbs-down': ['gestures'],
    'clap': ['gestures'],
    'wave': ['gestures'],
    'peace': ['gestures'],
    'victory': ['gestures'],
    'punch': ['gestures'],
    'muscle': ['body', 'fitness']
  };
  
  return categoryMap[iconName] || ['general'];
}
